# Generated by Django 5.2.10 on 2026-01-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_type', models.CharField(choices=[('PRIVATE', 'Private'), ('GOVERNMENT', 'Government')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
