/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/auth/token/": {
    /**
     * @description Takes a set of user credentials and returns an access and refresh JSON web
     * token pair to prove the authentication of those credentials.
     */
    post: operations["auth_token_create"];
  };
  "/v1/auth/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["auth_token_refresh_create"];
  };
  "/v1/banks/": {
    get: operations["banks_list"];
    post: operations["banks_create"];
  };
  "/v1/banks/{id}/": {
    get: operations["banks_retrieve"];
    put: operations["banks_update"];
    delete: operations["banks_destroy"];
    patch: operations["banks_partial_update"];
  };
  "/v1/clients/": {
    get: operations["clients_list"];
    post: operations["clients_create"];
  };
  "/v1/clients/{id}/": {
    get: operations["clients_retrieve"];
    put: operations["clients_update"];
    delete: operations["clients_destroy"];
    patch: operations["clients_partial_update"];
  };
  "/v1/credits/": {
    get: operations["credits_list"];
    post: operations["credits_create"];
  };
  "/v1/credits/{id}/": {
    get: operations["credits_retrieve"];
    put: operations["credits_update"];
    delete: operations["credits_destroy"];
    patch: operations["credits_partial_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Bank: {
      id: number;
      name: string;
      bank_type: components["schemas"]["BankTypeEnum"];
      address?: string;
    };
    /**
     * @description * `PRIVATE` - Private
     * * `GOVERNMENT` - Government
     * @enum {string}
     */
    BankTypeEnum: "PRIVATE" | "GOVERNMENT";
    Client: {
      id: number;
      full_name: string;
      /** Format: date */
      date_of_birth: string;
      /** @description Optional; if provided, it must match date of birth. */
      age?: number | null;
      nationality?: string;
      address?: string;
      /** Format: email */
      email: string;
      phone?: string;
      person_type?: components["schemas"]["PersonTypeEnum"];
      bank?: number | null;
      bank_name: string;
    };
    Credit: {
      id: number;
      client: number;
      client_full_name: string;
      description: string;
      /** Format: decimal */
      min_payment: string;
      /** Format: decimal */
      max_payment: string;
      /** Format: int64 */
      term_months: number;
      /** Format: date-time */
      created_at: string;
      bank: number;
      bank_name: string;
      credit_type: components["schemas"]["CreditTypeEnum"];
    };
    /**
     * @description * `AUTO` - Automotive
     * * `MORTGAGE` - Mortgage
     * * `COMMERCIAL` - Commercial
     * @enum {string}
     */
    CreditTypeEnum: "AUTO" | "MORTGAGE" | "COMMERCIAL";
    PaginatedBankList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Bank"][];
    };
    PaginatedClientList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Client"][];
    };
    PaginatedCreditList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["Credit"][];
    };
    PatchedBank: {
      id?: number;
      name?: string;
      bank_type?: components["schemas"]["BankTypeEnum"];
      address?: string;
    };
    PatchedClient: {
      id?: number;
      full_name?: string;
      /** Format: date */
      date_of_birth?: string;
      /** @description Optional; if provided, it must match date of birth. */
      age?: number | null;
      nationality?: string;
      address?: string;
      /** Format: email */
      email?: string;
      phone?: string;
      person_type?: components["schemas"]["PersonTypeEnum"];
      bank?: number | null;
      bank_name?: string;
    };
    PatchedCredit: {
      id?: number;
      client?: number;
      client_full_name?: string;
      description?: string;
      /** Format: decimal */
      min_payment?: string;
      /** Format: decimal */
      max_payment?: string;
      /** Format: int64 */
      term_months?: number;
      /** Format: date-time */
      created_at?: string;
      bank?: number;
      bank_name?: string;
      credit_type?: components["schemas"]["CreditTypeEnum"];
    };
    /**
     * @description * `NATURAL` - Natural
     * * `LEGAL_ENTITY` - Legal Entity
     * @enum {string}
     */
    PersonTypeEnum: "NATURAL" | "LEGAL_ENTITY";
    TokenObtainPair: {
      username: string;
      password: string;
      access: string;
      refresh: string;
    };
    TokenRefresh: {
      access: string;
      refresh: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * @description Takes a set of user credentials and returns an access and refresh JSON web
   * token pair to prove the authentication of those credentials.
   */
  auth_token_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenObtainPair"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
        "multipart/form-data": components["schemas"]["TokenObtainPair"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenObtainPair"];
        };
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  auth_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  banks_list: {
    parameters: {
      query?: {
        /**
         * @description * `PRIVATE` - Private
         * * `GOVERNMENT` - Government
         */
        bank_type?: "GOVERNMENT" | "PRIVATE";
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedBankList"];
        };
      };
    };
  };
  banks_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Bank"];
        "application/x-www-form-urlencoded": components["schemas"]["Bank"];
        "multipart/form-data": components["schemas"]["Bank"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Bank"];
        };
      };
    };
  };
  banks_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this bank. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Bank"];
        };
      };
    };
  };
  banks_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this bank. */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Bank"];
        "application/x-www-form-urlencoded": components["schemas"]["Bank"];
        "multipart/form-data": components["schemas"]["Bank"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Bank"];
        };
      };
    };
  };
  banks_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this bank. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  banks_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this bank. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedBank"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedBank"];
        "multipart/form-data": components["schemas"]["PatchedBank"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Bank"];
        };
      };
    };
  };
  clients_list: {
    parameters: {
      query?: {
        bank?: number;
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /**
         * @description * `NATURAL` - Natural
         * * `LEGAL_ENTITY` - Legal Entity
         */
        person_type?: "LEGAL_ENTITY" | "NATURAL";
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedClientList"];
        };
      };
    };
  };
  clients_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Client"];
        "application/x-www-form-urlencoded": components["schemas"]["Client"];
        "multipart/form-data": components["schemas"]["Client"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
    };
  };
  clients_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this client. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
    };
  };
  clients_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this client. */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Client"];
        "application/x-www-form-urlencoded": components["schemas"]["Client"];
        "multipart/form-data": components["schemas"]["Client"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
    };
  };
  clients_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this client. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  clients_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this client. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedClient"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedClient"];
        "multipart/form-data": components["schemas"]["PatchedClient"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Client"];
        };
      };
    };
  };
  credits_list: {
    parameters: {
      query?: {
        bank?: number;
        /**
         * @description * `AUTO` - Automotive
         * * `MORTGAGE` - Mortgage
         * * `COMMERCIAL` - Commercial
         */
        credit_type?: "AUTO" | "COMMERCIAL" | "MORTGAGE";
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description A search term. */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedCreditList"];
        };
      };
    };
  };
  credits_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Credit"];
        "application/x-www-form-urlencoded": components["schemas"]["Credit"];
        "multipart/form-data": components["schemas"]["Credit"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["Credit"];
        };
      };
    };
  };
  credits_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this credit. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Credit"];
        };
      };
    };
  };
  credits_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this credit. */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Credit"];
        "application/x-www-form-urlencoded": components["schemas"]["Credit"];
        "multipart/form-data": components["schemas"]["Credit"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Credit"];
        };
      };
    };
  };
  credits_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this credit. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  credits_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this credit. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedCredit"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedCredit"];
        "multipart/form-data": components["schemas"]["PatchedCredit"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["Credit"];
        };
      };
    };
  };
}
