# Generated by Django 5.2.10 on 2026-01-19 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('min_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit_type', models.CharField(choices=[('AUTO', 'Automotive'), ('MORTGAGE', 'Mortgage'), ('COMMERCIAL', 'Commercial')], max_length=32)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='banks.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='clients.client')),
            ],
        ),
    ]
